version: "3.2"
services:
    php:
        build: "./php/"
        networks:
            - backend
        volumes:
            - ./src:/var/www/html/
    apache:
        build: "./apache/"
        depends_on:
            - php
            - mysql
        networks:
            - frontend
            - backend
        ports:
            - "80:80"
        volumes:
            - ./src:/var/www/html/
        links:
            - mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            - PMA_HOST=mysql
        depends_on:
            - mysql
        restart: always
        ports:
            - 8080:80
        networks:
            - backend

    mysql:
        image: mysql:5.7
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 3306:3306
        volumes:
            - ./mysql:/var/lib/mysql
        networks:
            - frontend
            - backend

networks:
    frontend:
    backend:
